adventure_quest_project/adventureQuest/urls.py
from django.conf.urls import url
from adventureQuest import views

############################################
#   This is the urls for Adventure Quest   #
############################################

urlpatterns = [

	# Home Page
	url(r'^$', views.index, name='index'),

	# Hall of Fame
	url(r'^hall_of_fame/$', views.hall_of_fame, name='hall_of_fame'),

	# Congratulations page for when you complete a quest.
	url(r'^congratulations/$', views.congratulations, name='congratulations'),

	# URL's for posting a Hall of Fame Post and for making and displaying comments.
	url(r'^post_form/$', views.post_create, name='post_form'),
	url(r'^comment/$', views.comment, name='comment'),
	url(r'^comment_form/$', views.add_comment, name='add_comment'),

	# URL's to do with user login functionality
	url(r'^register/$',views.register,name='register'),
	url(r'^login/$', views.user_login, name='login'),
	url(r'^logout/$', views.user_logout, name='logout'),
	url(r'^my_account/$', views.my_account, name='my_account'),

	# URL's for the quest about pages.
	url(r'^mystery_about/$', views.mystery_about, name='mystery_about'),
	url(r'^finnieston_about/$', views.finnieston_about, name='finnieston_about'),
	url(r'^glasgow_uni_about/$', views.glasgow_uni_about, name='glasgow_uni_about'),
	url(r'^southside_about/$', views.southside_about, name='southside_about'),
	url(r'^city_centre_about/$', views.city_centre_about, name='city_centre_about'),
	url(r'^kids_about/$', views.kids_about, name='kids_about'),

	# URL's for the quest riddle pages.
	url(r'^mystery_quest/$', views.mystery_quest, name='mystery_quest'),
	url(r'^finnieston_quest/$', views.finnieston_quest, name='finnieston_quest'),
	url(r'^glasgow_uni_quest/$', views.glasgow_uni_quest, name='glasgow_uni_quest'),
	url(r'^southside_quest/$', views.southside_quest, name='southside_quest'),
	url(r'^city_centre_quest/$', views.city_centre_quest, name='city_centre_quest'),
	url(r'^kids_quest/$', views.kids_quest, name='kids_quest'),

	# URL's for the quest hall of fame pages.
	url(r'^mystery_quest_hall_of_fame/$', views.mystery_quest_hall_of_fame, name='mystery_quest_hall_of_fame'),
	url(r'^finnieston_quest_hall_of_fame/$', views.finnieston_quest_hall_of_fame, name='finnieston_quest_hall_of_fame'),
	url(r'^glasgow_uni_quest_hall_of_fame/$', views.glasgow_uni_quest_hall_of_fame, name='glasgow_uni_quest_hall_of_fame'),
	url(r'^southside_quest_hall_of_fame/$', views.southside_quest_hall_of_fame, name='southside_quest_hall_of_fame'),
	url(r'^city_centre_quest_hall_of_fame/$', views.city_centre_quest_hall_of_fame, name='city_centre_quest_hall_of_fame'),
	url(r'^kids_quest_hall_of_fame/$', views.kids_quest_hall_of_fame, name='kids_quest_hall_of_fame'),

	# URL for ajax functionality to handle riddle logic.
	url(r'^quest_ajax/$', views.quest_ajax, name='quest_ajax'),

]

adventure_quest_project/adventure_quest_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from adventureQuest import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'^$', views.index, name='index'),
	#Maps urls from the app folder
	url(r'^adventureQuest/', include('adventureQuest.urls')),
    url(r'^admin/', admin.site.urls),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adventure_quest_project/adventureQuest/models.py
from __future__ import unicode_literals
from django.contrib import admin
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.conf import settings
from datetime import datetime
from django.template.defaultfilters import slugify
import ast



######################
#   Helper methods   #
######################


# This is a helper methods to allow list fields for models
class ListField(models.TextField):

    def __init__(self, *args, **kwargs):
        super(ListField, self).__init__(*args, **kwargs)

    def to_python(self, value):
        if not value:
            value = []

        if isinstance(value, list):
            return value

        return ast.literal_eval(value)

    def get_prep_value(self, value):
        if value is None:
            return value

        return unicode(value)

    def value_to_string(self, obj):
        value = self._get_val_from_obj(obj)
        return self.get_db_prep_value(value)


# Helper method to create an upload location for image files
def upload_location(instance, filename):
    return "%s/%s" % (instance.id, filename)


##############################################
#   This is our models for Adventure Quest   #
##############################################


# The UserProfile model stores information about each user.
class UserProfile(models.Model):
    # This links UserProfile to a User model instance.
    user = models.OneToOneField(User)
    # A profile picture for the user
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

    def __unicode__(self):
        return self.user.username


# The Riddle model stores information for each riddle in the quest.
class Riddle(models.Model):
    question = models.CharField(max_length=128)
    answer = ListField()
    instruction = models.CharField(max_length=128, default='No specific instructions available')
    hint = models.CharField(max_length=128, default='No hint available')
    question_id = models.IntegerField(default=0)
    quest_name = models.CharField(max_length=128)

    def __int__(self):
        return self.question_id


# The Quest model stores information about each different quest.
class Quest(models.Model):
    name = models.CharField(max_length=200, default='new Quest')
    description = models.TextField()
    difficulty = models.CharField(max_length=120)
    age_limit = models.IntegerField(default=0)
    start_point = models.CharField(max_length=120, default = 'here')

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name


# This is a model to represent the user's scores after they've completed a quest
class UserScores(models.Model):
    user = models.ForeignKey(User)
    quest = models.ForeignKey(Quest)
    score = models.IntegerField(default=1000)

    def __str__(self):
        return self.user

    def __unicode__(self):
        return self.user


# Post to upload images
class Post(models.Model):
    user = models.ForeignKey(User, default=1)
    quest = models.ForeignKey(Quest)
    title = models.CharField(max_length=120)
    image = models.ImageField(upload_to=upload_location,
                              null=True,
                              blank=True,
                              width_field="width_field",
                              height_field="height_field")
    height_field = models.IntegerField(default=0)
    width_field = models.IntegerField(default=0)
    content = models.TextField()
    hints = models.IntegerField(default=10000)
    updated = models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    class Meta:
        ordering = ["-timestamp", "-updated"]


# Model for comments
class Comment(models.Model):
    quest = models.ForeignKey(Quest)
    author = models.CharField(max_length=128)
    text = models.TextField()
    created_date = models.DateTimeField(default=datetime.now)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.text

    def __unicode__(self):
        return self.text

adventure_quest_project/adventureQuest/views.py
from django.shortcuts import render, render_to_response, redirect
from django.http import HttpResponse
from django.shortcuts import render
from adventureQuest.forms import UserForm, UserProfileForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from adventureQuest.models import Quest, Riddle
from django.shortcuts import redirect
from adventureQuest.models import Quest, Riddle, UserProfile, UserScores
from django.core.signals import request_finished
from .forms import PostForm, CommentForm
from .models import Quest, Riddle, UserProfile, Post, Comment
import re
import json

#############################################
#   This is the views for Adventure Quest   #
#############################################


# The home page, has info about Adventure Quest and links to the other
# parts of the application.
def index(request):
    return render(request, 'adventureQuest/index.html')


# Quest comments
def comment(request):
    objects_comment = Comment.objects.all()
    context={
        "comment_list": objects_comment,
    }
    return render(request, 'adventureQuest/comment.html', context)


# Adding comments
def add_comment(request):
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.save()
            return redirect('comment')
    else:
        form = CommentForm()
    return render(request, 'adventureQuest/comment_form.html', {'form': form})


# The about page for the Finnieston Quest displays information about the
# Quest, a map of the starting location and a link to begin the quest.
def finnieston_about(request):
    context_dict = {}
    context_dict['questurl'] = reverse(finnieston_quest)
    context_dict['questmappos'] = "55.868273, -4.292110" 
    for row in Quest.objects.filter(name="finnieston_quest"):
        context_dict['descr'] = row.description
        context_dict['age_limit'] = row.age_limit
        context_dict['difficulty'] = row.difficulty
        context_dict['start'] = row.start_point

    check_url(request)
    return render(request, 'adventureQuest/finnieston_about.html', context_dict)


# The about page for the Glasgow University Quest displays information about the
# Quest, a map of the starting location and a link to begin the quest.
def glasgow_uni_about(request):
    context_dict = {}
    context_dict['questurl'] = reverse(glasgow_uni_quest)
    context_dict['questmappos'] = "55.871950, -4.288233"
    for row in Quest.objects.filter(name="glasgow_uni_quest"):
        context_dict['descr'] = row.description
        context_dict['age_limit'] = row.age_limit
        context_dict['difficulty'] = row.difficulty
        context_dict['start'] = row.start_point
    check_url(request)
    return render(request, 'adventureQuest/glasgow_uni_about.html', context_dict)


# The about page for the Southside Quest displays information about the
# Quest, a map of the starting location and a link to begin the quest.
def southside_about(request):
    context_dict = {}
    context_dict['questurl'] = reverse(southside_quest)
    context_dict['questmappos'] = "55.840240, -4.267360"
    for row in Quest.objects.filter(name="southside_quest"):
        context_dict['descr'] = row.description
        context_dict['age_limit'] = row.age_limit
        context_dict['difficulty'] = row.difficulty
        context_dict['start'] = row.start_point
    check_url(request)
    return render(request, 'adventureQuest/southside_about.html', context_dict)


# The about page for the City Centre Quest displays information about the
# Quest, a map of the starting location and a link to begin the quest.
def city_centre_about(request):
    context_dict = {}
    context_dict['questurl'] = reverse(city_centre_quest)
    context_dict['questmappos'] = "55.859986, -4.252588"
    for row in Quest.objects.filter(name="city_centre_quest"):
        context_dict['descr'] = row.description
        context_dict['age_limit'] = row.age_limit
        context_dict['difficulty'] = row.difficulty
        context_dict['start'] = row.start_point
    check_url(request)
    return render(request, 'adventureQuest/city_centre_about.html', context_dict)


# The about page for the Kids Quest displays information about the
# Quest, a map of the starting location and a link to begin the quest.
def kids_about(request):
    context_dict = {}
    context_dict['questurl'] = reverse(kids_quest)
    context_dict['questmappos'] = "55.868786, -4.290196"
    for row in Quest.objects.filter(name="kids_quest"):
        context_dict['descr'] = row.description
        context_dict['age_limit'] = row.age_limit
        context_dict['difficulty'] = row.difficulty
        context_dict['start'] = row.start_point
    check_url(request)
    return render(request, 'adventureQuest/kids_about.html', context_dict)


# The about page for the Mystery Quest displays information about the
# Quest, a map of the starting location and a link to begin the quest.
def mystery_about(request):
    context_dict = {}
    context_dict['questurl'] = reverse(mystery_quest)
    context_dict['questmappos'] = "55.856908, -4.246374"
    for row in Quest.objects.filter(name="mystery_quest"):
        context_dict['descr'] = row.description
        context_dict['age_limit'] = row.age_limit
        context_dict['difficulty'] = row.difficulty
        context_dict['start'] = row.start_point
        
    check_url(request)
    return render(request, 'adventureQuest/mystery_about.html', context_dict)


# The view for the congratulations page
def congratulations(request):
    return render(request, 'adventureQuest/congratulations.html')


# The view for the registration page. Allows users to register with a username,
# email and password and an optional profile pciture.
def register(request):
    # Tells us if registration was successful or not.
    registered = False
    # Try and get form info with POST.
    if request.method == 'POST':
        user_form = UserForm(request.POST or None, request.FILES or None)
        profile_form = UserProfileForm(request.POST or None, request.FILES or None)
        # If the two forms are valid:
        if user_form.is_valid() and profile_form.is_valid():

            # Save the user's form data to the database.
            user = user_form.save()

            # Hash the users password and then update the user object.
            user.set_password(user.password)
            user.save()

            # Set commit=False to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Check if user uploaded a profile picture.
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update variable as registration was successful.
            registered = True
        else:
            # Print problems to the terminal.
            print(user_form.errors, profile_form.errors)

    else:
        # Not a HTTP POST, so we render our form using two ModelForm instances.
        # These forms will be blank, ready for user input.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
                  'adventureQuest/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered, })



# The My Account page view. This view allows information to be displayed about the
# quests the user has completed and their high scores, their profile picture and
# any hall of fame posts they have made.
def my_account(request):
    # Get current user.
    user = request.user

    # Get all the hall of fame posts made by user and order them by number of hints used low-high.
    objects_filter = Post.objects.filter(user=user)
    objects_post = objects_filter.order_by('hints')[:100]

    # Add the posts to the context dictionary.
    context_dict = {"object_list": objects_post,}

    # Initialise each quest so that if they haven't completed the quest n/a will appear.
    context_dict['mystery_quest'] = 'n/a'
    context_dict['finnieston_quest'] = 'n/a'
    context_dict['glasgow_uni_quest'] = 'n/a'
    context_dict['southside_quest'] = 'n/a'
    context_dict['city_centre_quest'] = 'n/a'
    context_dict['kids_quest'] = 'n/a'

    # Get the user information to be displayed on the page.
    for row in UserProfile.objects.filter(user=user):
        context_dict['user'] = row.user
        context_dict['pic'] = str(row.picture)

    # Order the number of hints so that best scores are at the top.
    all_scores = UserScores.objects.filter(user=request.user)
    ordered_scores = all_scores.order_by('-score')

    # Get the least amount of hints used for each quest and update context dictionary.
    for row in ordered_scores.filter(user=request.user):
        context_dict[row.quest.name] = row.score

    return render(request, 'adventureQuest/my_account.html',context_dict)


# The view for login page. Authenticates users who provide valid log in details.
def user_login(request):
    context_dict = {}
    # If the request is a POST, try to get the information.
    if request.method == 'POST':
        # Get the username and password provided by the user.
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Check if the username/password combination is valid,
        # a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # Check if a User object was returned.

adventure_quest_project/templates/adventureQuest/city_centre_about.html
{% extends "adventureQuest/base.html" %}
{% load staticfiles %}

{% block Title %}City Centre Quest About{% endblock %}

<!-- displays basic Quest information on a scroll -->
<!-- allows user to start playing the City Centre Quest -->
{% block body_block %}  
<div id="bg">
  <img src="{% static "images/mapbg.jpg" %}" alt="">
</div>
<!-- Include tag to include HTML from quest about generic template-->
{% include "adventureQuest/quest_about.html" %}

    
{% endblock %}

adventure_quest_project/templates/adventureQuest/comment.html
{% extends "adventureQuest/base.html" %}
{% load staticfiles %}

{% block Title %}Comments{% endblock %}


{% block body_block %}


<!-- Comments box. Shows all comments from database-->
<div class="w3-content w3-container w3-padding-64 w3-card-2 w3-sand" id="comments">
  <h1 class="w3-center">Comments</h1>
  
<!-- only registered users who are logged in can leave a comment -->
    {% if user.is_authenticated %}
        <a class="w3-btn w3-round-large" href="{% url 'add_comment' %}">Add comment</a>
 <!-- prompt user to login in order to comment -->
    {% else %}
         <a href="{% url 'login' %}">Login before commenting</a>
    {% endif %}
    <hr>
    <!-- display list of all comments -->
    {% for comment in comment_list %}
        <div class="w3-container w3-card-2 w3-padding-bottom w3-white ">
            <div class="w3-panel w3-large w3-center">
                <p>{{ comment.text|linebreaks }}</p>
            </div>
            
            <li class="horizontal w3-padding-right"> Quest: {{ comment.quest }}</li>
            <li class="horizontal w3-padding-right"> Date: {{ comment.created_date }}</li>
            <li class="horizontal w3-padding-right"> Author: {{ comment.author }}</li>
        </div>
        <br>
    {% endfor %}
</div>
{% endblock %}

adventure_quest_project/templates/adventureQuest/comment_form.html
{% extends 'adventureQuest/base.html' %}

{% block title_block  %}
Comment
{% endblock  %}

<!-- allows users to add comments to a selected quest -->
{% block body_block %}
<div class = 'w3-content w3-padding-64 w3-center'>

<h1>New comment</h1>
    <form method="POST" class="post-form w3-container w3-center w3-card-16 w3-hover-questy">
        {% csrf_token %}
        <!-- drop-down menu to choose a quest -->
        <div class="w3-center w3-panel" style="width: 100%; display: inline-block">
            <p><label for="id_quest">Quest:</label> <select id="id_quest" name="quest">
            <option value="" selected="selected">Choose a Quest</option>
            <option value="1">mystery_quest</option>
            <option value="2">finnieston_quest</option>
            <option value="3">southside_quest</option>
            <option value="4">glasgow_uni_quest</option>
            <option value="5">kids_quest</option>
            </select></p>
            <p><label for="id_author">Author:</label> <input id="id_author" maxlength="128" name="author" type="text"></p>
            <label for="id_text">Your Comment:</label>
            <!-- enter your comment here -->
            <p><textarea cols="100" id="id_text" name="text" rows="5"></textarea></p>
        
        <button type="submit" class="save btn btn-default">Submit</button>
        </div>
    </form>
    <div>
       <!-- links back to comment page where all comments are displayed -->
        <p> <a href="/adventureQuest/comment/">Return</a> to all Comments</p>
    </div>
</div>
{% endblock  %}

adventure_quest_project/templates/adventureQuest/finnieston_about.html
{% extends "adventureQuest/base.html" %}
{% load staticfiles %}

{% block title_block %}Finnieston Quest About{% endblock %}

<!-- displays basic Quest information on a scroll -->
<!-- allows user to start playing the Finnieston Quest -->
{% block body_block %}  

<div id="bg">
  <img src="{% static "images/mapbg.jpg" %}" alt="">
</div>
<!-- Include tag to include HTML from quest about generic template-->
{% include "adventureQuest/quest_about.html" %}



	
{% endblock %}

adventure_quest_project/templates/adventureQuest/finnieston_quest.html
{% extends "adventureQuest/base.html" %}
{% load staticfiles %}
<!-- SS and KJ Adding JQuery functionality -->


{% block title_block %}
    Finnieston Quest - Riddle (get no. from database)


{% endblock %}

<!-- Finnieston Quest riddles -->
<!-- Note that some quests only have a limited amount of information to demonstrate core functionalities -->
<!-- the full number of riddles and options will be implemented in a later release following additional reserach -->
{% block body_block %}
<div id="bg">
  <img src="{% static "images/mapbg.jpg" %}" alt="">
</div>
<br><br><br><br>
<div class="w3-content w3-container w3-padding-64" id="aboutquest">
    <div class="quest_scroll w3-display-container">
        <img src="{% static "images/scroll.png" %}" style="width:100%"></a>
    
        <div class="w3-display-middle w3-text-black" style="font-size: 18px;">
            <div class="w3-container">
               <h1>QUEST!!</h1>
		<div id="instruction">
			This is just a fun riddle to complete while you have a drink
		</div>
		<div class="w3-large" id="answer">
			<p>What is greater than God, more evil than the devil, the poor have it, the rich need it, and if you eat it, you'll die?</p>
		</div>
		<hr />
        <div>
			Type your answer below and press submit:
			<br/>
            <form id="questionform">
				<input id="question" />
				<input type="submit" />
			</form>
        </div>
		<div id="hint">
			Your hint will appear here....but remember the number of hints you use will be recorded!
		</div>
        <div>
            <form id="hintform">
				<input type="button" id = "hint_button" value = "Hint"/>
			</form>
        </div>
        <div>
          	Number of hints used:
        </div>
		<div id="hintNo">
			0
		</div>
    </div>    
            
        
	</div>
</div>
		<!-- fix this -->
		<script src="{% static 'js/jquery.min.js' %}"> </script>
		<script src="{% static 'js/adventureQuest-jquery.js' %}"> </script>
{% endblock %}

adventure_quest_project/templates/adventureQuest/finnieston_quest_post_list.html
{% extends 'adventureQuest/base.html' %}

{% block title_block  %}
Photo Gallery
{% endblock  %}

<!-- Finnieston Hall of Fame -->
{% block body_block %}

<div class = 'w3-content w3-center'>
    <div>
        <h1>Finnieston Quest Hall of Fame</h1>
    </div>
 </div>
       <!-- display all entries for the Finnieston Hall of Fame -->
    {% for obj in object_list %}
        {% if obj.image %}
        <div class = 'w3-content w3-center'>
            <div style="display:inline; text-align:left;"><img src='{{ obj.image.url }}' class='img-responsive'/></div>
            <div style="float: right"><ul>
               <ul>Title: {{obj.title}}</ul>
                   <ul>Uploaded by: {{obj.user}}</ul>
                   <ul>Comment: {{obj.content}}</ul>
                   <ul>Quest: {{obj.quest}}</ul>
                   <ul>Date: {{obj.timestamp}}</ul>
                {% if obj.hints != 10000 %}
                    <ul>Hints used:{{obj.hints}}</ul>
                {% else %}
                    <ul>{{obj.user}} is still to conquer this quest!</ul>
                {% endif %}
            </ul></div>
            <br><br><br><br>
        </div>
        {% endif %}
{% endfor %}


{% endblock %}}

adventure_quest_project/templates/adventureQuest/glasgow_uni_quest.html
{% extends "adventureQuest/base.html" %}
{% load staticfiles %}
<!-- SS and KJ Adding JQuery functionality -->

<!-- Glasgow University Quest riddles -->
<!-- Note that some quests only have a limited amount of information to demonstrate core functionalities -->
<!-- the full number of riddles and options will be implemented in a later release following additional reserach -->
{% block title_block %}
    Glasgow University Quest - Riddle (get no. from database)
{% endblock %}

{% block body_block %}
<div id="bg">
  <img src="{% static "images/mapbg.jpg" %}" alt="">
</div>
<br><br><br><br>
<div class="w3-content w3-container w3-padding-64" id="aboutquest">
    <div class="quest_scroll w3-display-container">
        <img src="{% static "images/scroll.png" %}" style="width:100%"></a>
    
        <div class="w3-display-middle w3-text-black" style="font-size: 18px;">
            <div class="w3-container">
               <h1>QUEST!!</h1>
			<div>
				Type your answer below and press submit:
			</div>
			<br/>
			<div id="instruction">
				This is just a fun riddle to complete while you have a drink
			</div>
			<div class="w3-large" id="answer">
				Which famous inventor studied at Glasgow University in 1914?
			</div>
			<hr />
			<div>
				<form id="questionform">
					<input id="question" />
					<input type="submit" />
				</form>
			</div>
			<div id="hint">
				Your hint will appear here....but remember the number of hints you use will be recorded!
			</div>
			<div>
				<form id="hintform">
					<input type="button" id = "hint_button" value = "Hint"/>
				</form>
			</div>
			<div>
				Number of hints used:
			</div>
			<div id="hintNo">
				0
			</div>
		</div>
            
        
	</div>
</div>
		<!-- fix this -->
		<script src="{% static 'js/jquery.min.js' %}"> </script>
		<script src="{% static 'js/adventureQuest-jquery.js' %}"> </script>
{% endblock %}

adventure_quest_project/templates/adventureQuest/kids_quest.html
{% extends "adventureQuest/base.html" %}
{% load staticfiles %}
<!-- SS and KJ Adding JQuery functionality -->


{% block title_block %}
    Kids Quest - Riddle (get no. from database)
{% endblock %}

<!-- Kids Quest riddles -->
<!-- Note that some quests only have a limited amount of information to demonstrate core functionalities -->
<!-- the full number of riddles and options will be implemented in a later release following additional reserach -->
{% block body_block %}
<div id="bg">
  <img src="{% static "images/mapbg.jpg" %}" alt="">
</div>
<br><br><br><br>
<div class="w3-content w3-container w3-padding-64" id="aboutquest">
    <div class="quest_scroll w3-display-container">
        <img src="{% static "images/scroll.png" %}" style="width:100%"></a>
    
        <div class="w3-display-middle w3-text-black" style="font-size: 18px;">
            <div class="w3-container">
               <h1>QUEST!!</h1>
				<div>
					Type your answer below and press submit:
				</div>
				<br/>
				<div id="instruction">
					This is just a fun riddle to complete while you have a drink of orange juice
				</div>
				<div class="w3-large" id="answer">
					What has a face and two hands but no arms or legs?
				</div>
				<hr />
				<div>
					<form id="questionform">
						<input id="question" />
						<input type="submit" />
					</form>
				</div>
				<div id="hint">
					Your hint will appear here....but remember the number of hints you use will be recorded!
				</div>
				<div>
					<form id="hintform">
						<input type="button" id = "hint_button" value = "Hint"/>
					</form>
				</div>
				<div>
					Number of hints used:
				</div>
				<div id="hintNo">
					0
				</div>
		</div>
	</div>
</div>
		<!-- fix this -->
		<script src="{% static 'js/jquery.min.js' %}"> </script>
		<script src="{% static 'js/adventureQuest-jquery.js' %}"> </script>
{% endblock %}

adventure_quest_project/templates/adventureQuest/mystery_about.html
{% extends "adventureQuest/base.html" %}
{% load staticfiles %}

{% block title_block %}Mystery Quest About{% endblock %}

<!-- displays basic Quest information on a scroll -->
<!-- allows user to start playing the Mystery Quest -->
{% block body_block %}  
<div id="bg">
  <img src="{% static "images/mapbg.jpg" %}" alt="">
</div>
<!-- Include tag to include HTML from quest about generic template-->
{% include "adventureQuest/quest_about.html" %}

{% endblock %}

adventure_quest_project/templates/adventureQuest/register.html
{% extends 'adventureQuest/base.html' %}
{% load staticfiles %}
{% block title_block %}
    Register
{% endblock %}
<!-- lets users register for the site -->
{% block body_block %}
<div class="w3-content w3-container w3-padding-64 w3-center">
    <!-- checks if user is already registered and provides link back to homepage -->
    {% if registered %}
        <h2>Thank You!
        <a href="{% url 'index' %}">Return to the homepage.</a>
        </h2>    
        <br/>
    {% else %}
         Sorry there was a problem, please try again
        <h2>Register Here</h2>
    {% endif %}
    <form class="w3-container w3-card-4 w3-hover-questy" id="user_form" method="post" action="{% url 'register' %}"
              enctype="multipart/form-data">
    {% csrf_token %}
       <!-- Display each form -->
        <!-- User is prompted for following information -->
            <p><label for="id_username" class="w3-tooltip">Username:
                <span class="w3-text">Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.</span></label> 
                <input id="id_username" class="w3-input w3-border" maxlength="30" name="username" type="text"></p>
        <p><label for="id_email">Email address:</label> 
            <input id="id_email" class="w3-input w3-border" maxlength="254" name="email" type="email"></p>
        <p><label for="id_password">Password:</label> 
            <input id="id_password" class="w3-input w3-border" name="password" type="password"></p>
            <p><img id="preview" alt="Optionally: Upload a pic" width="100" height="100" /><br/>
                <label for="id_picture" class="w3-button w3-white w3-hover-red">Upload</label>
                <input id=id_picture name="picture" type="file" style="display: none;" onchange="document.getElementById('preview').src = window.URL.createObjectURL(this.files[0])"></p>
    <button class="w3-btn w3-white" type="submit" name="submit" value="Register">Register</button>
    </form>
    <br/>
</div>
{% endblock %}